ssl_cert_file: x509/actual.cert.pem
ssl_key_file:  x509/actual.key.pem
listen_port: 1638
#listen_addr:

# authentication subsystem
auth_method: Authen::Simple::Passwd
auth_params:
  path: passwords.htp

methods:
  - "procedures/*/*.pm"
