ssl_cert_file: x509/actual.cert.pem
ssl_key_file:  x509/actual.key.pem
listen_port: 1638
#listen_addr:

# authentication subsystem
auth_method: Authen::Simple::Passwd
auth_params:
  path: passwords.htp

methods:
  - "procedures/*/*.pm"

caller:
  rudolf:
    hostname: 192.168.2.100
    port: 16333
    username: nabla
    password: qwerty
    ca_ignore: true
    #verify_hostname: true
  hans:
    hostname: hans.jarowit.net
    #port: 3033
    username: nabla
    password: nabla
    ca_file: x509/actual.cert.pem
    #verify_hostname: true
  local:
    hostname: localhost
    #port: 3033
    username: nabla
    password: nabla
    ca_file: x509/actual.cert.pem
    verify_hostname: false
