ssl_cert_file: x509/actual.cert.pem
ssl_key_file:  x509/actual.key.pem
listen_port: 1638
#listen_addr:

# authentication subsystem
auth_method: Authen::Simple::Passwd
auth_params:
  path: passwords.htp

methods:
  - "procedures/*/*.pm"

xmlrpcaller:
  # example:
  #   hostname: <mandatory>
  #   port: 3306
  #   username: <required-for-http-authentication>
  #   password: <will-be-asked-if-omited>
  #   ca_file: <required-if-ca_ignore-false>
  #   ca_ignore: false
  #   verify_hostname: true
  rudolf:
    hostname: 192.168.2.100
    port: 16333
    username: nabla
    password: qwerty
    ca_ignore: true
  hans:
    hostname: hans.jarowit.net
    port: 1638
    username: nabla
    #password: nabla
    ca_file: x509/actual.cert.pem
  local:
    hostname: localhost
    port: 1638
    username: nabla
    #password: nabla
    ca_file: x509/actual.cert.pem
    verify_hostname: false
